---

version: "3"

services:
  payments:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
      - "4000:4000"
    volumes:
      - ./assets:/app/assets
      - ./config:/app/config
      - ./lib:/app/lib
      - ./priv:/app/priv
      - ./test:/app/test
    command: do ecto.create, phx.server
    working_dir: /opt/app
    depends_on:
      - postgres

  postgres:
    image: timescale/timescaledb:latest-pg11
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
