---

name: Update

on:
  schedule:
    - cron:  "0 0 * * *"

jobs:
  Translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: docker-compose build

      - name: Extract
        run: docker-compose run payments gettext.extract --merge

      - name: Push
        run: |
          git config --local user.email "webdev@elementary.io"
          git config --local user.name "elementaryBot"

          git add priv/gettext
          git commit -m "l10n: update gettext templates"

          git push
